# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a79b1c2fe19f0dab6444fa3535c252a6d7fca6caf279fdfb8f74c81f503b315128da856f347391b83ae2be938ac6c7356c2ebfa3f76fa457198e39d214d682

test:
  secret_key_base: 32906d55d5b875fcf31655caab02327bc4e44187080a6bbf97ff57303d514a783c4bec8a91a959b85a3ccf30f55c3d3d3e7fcb38a7061205eb0887df8285b2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
